language: python

python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"

matrix:
  include:
    - python: 3.8
      script: python setup.py test

install:
  - pip install 'flake8' 'coverage<4' coveralls

script:
  - coverage run setup.py test
  - flake8 requirements

after_success: coveralls
