language: python

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"

install:
  - pip install 'flake8<3' 'coverage<4' coveralls

script:
  - coverage run setup.py test
  - flake8 requirements

after_success: coveralls
